//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace sikusiSubtitles.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MicID {
            get {
                return ((string)(this["MicID"]));
            }
            set {
                this["MicID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Chrome")]
        public string RecognitionEngine {
            get {
                return ((string)(this["RecognitionEngine"]));
            }
            set {
                this["RecognitionEngine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SystemSpeechRecognitionLanguage {
            get {
                return ((string)(this["SystemSpeechRecognitionLanguage"]));
            }
            set {
                this["SystemSpeechRecognitionLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AzureSpeechRecognitionKey {
            get {
                return ((string)(this["AzureSpeechRecognitionKey"]));
            }
            set {
                this["AzureSpeechRecognitionKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AzureSpeechRecognitionRegion {
            get {
                return ((string)(this["AzureSpeechRecognitionRegion"]));
            }
            set {
                this["AzureSpeechRecognitionRegion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string ObsIP {
            get {
                return ((string)(this["ObsIP"]));
            }
            set {
                this["ObsIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4455")]
        public int ObsPort {
            get {
                return ((int)(this["ObsPort"]));
            }
            set {
                this["ObsPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ObsPassword {
            get {
                return ((string)(this["ObsPassword"]));
            }
            set {
                this["ObsPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SubtitlesVoice {
            get {
                return ((string)(this["SubtitlesVoice"]));
            }
            set {
                this["SubtitlesVoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TtranslationService {
            get {
                return ((string)(this["TtranslationService"]));
            }
            set {
                this["TtranslationService"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AzureTranslationKey {
            get {
                return ((string)(this["AzureTranslationKey"]));
            }
            set {
                this["AzureTranslationKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AzureTranslationRegion {
            get {
                return ((string)(this["AzureTranslationRegion"]));
            }
            set {
                this["AzureTranslationRegion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AzureTranslationFrom {
            get {
                return ((string)(this["AzureTranslationFrom"]));
            }
            set {
                this["AzureTranslationFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AzureTranslationTo1 {
            get {
                return ((string)(this["AzureTranslationTo1"]));
            }
            set {
                this["AzureTranslationTo1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AzureTranslationTo2 {
            get {
                return ((string)(this["AzureTranslationTo2"]));
            }
            set {
                this["AzureTranslationTo2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AzureTranslationTo1Run {
            get {
                return ((bool)(this["AzureTranslationTo1Run"]));
            }
            set {
                this["AzureTranslationTo1Run"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AzureTranslationTo2Run {
            get {
                return ((bool)(this["AzureTranslationTo2Run"]));
            }
            set {
                this["AzureTranslationTo2Run"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14949")]
        public int ChromePort {
            get {
                return ((int)(this["ChromePort"]));
            }
            set {
                this["ChromePort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GoogleTranslationBasicKey {
            get {
                return ((string)(this["GoogleTranslationBasicKey"]));
            }
            set {
                this["GoogleTranslationBasicKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GoogleTranslationBasicFrom {
            get {
                return ((string)(this["GoogleTranslationBasicFrom"]));
            }
            set {
                this["GoogleTranslationBasicFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GoogleTranslationBasicTo1 {
            get {
                return ((string)(this["GoogleTranslationBasicTo1"]));
            }
            set {
                this["GoogleTranslationBasicTo1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GoogleTranslationBasicTo2 {
            get {
                return ((string)(this["GoogleTranslationBasicTo2"]));
            }
            set {
                this["GoogleTranslationBasicTo2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GoogleTranslationBasicTo1Run {
            get {
                return ((bool)(this["GoogleTranslationBasicTo1Run"]));
            }
            set {
                this["GoogleTranslationBasicTo1Run"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GoogleTranslationBasicTo2Run {
            get {
                return ((bool)(this["GoogleTranslationBasicTo2Run"]));
            }
            set {
                this["GoogleTranslationBasicTo2Run"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AmiVoiceKey {
            get {
                return ((string)(this["AmiVoiceKey"]));
            }
            set {
                this["AmiVoiceKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AmiVoiceEngine {
            get {
                return ((string)(this["AmiVoiceEngine"]));
            }
            set {
                this["AmiVoiceEngine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AmiVoiceLog {
            get {
                return ((bool)(this["AmiVoiceLog"]));
            }
            set {
                this["AmiVoiceLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ChromeLanguage {
            get {
                return ((string)(this["ChromeLanguage"]));
            }
            set {
                this["ChromeLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GoogleAppsScriptTranslationKey {
            get {
                return ((string)(this["GoogleAppsScriptTranslationKey"]));
            }
            set {
                this["GoogleAppsScriptTranslationKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GoogleAppsScriptTranslationFrom {
            get {
                return ((string)(this["GoogleAppsScriptTranslationFrom"]));
            }
            set {
                this["GoogleAppsScriptTranslationFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GoogleAppsScriptTranslationTo1 {
            get {
                return ((string)(this["GoogleAppsScriptTranslationTo1"]));
            }
            set {
                this["GoogleAppsScriptTranslationTo1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GoogleAppsScriptTranslationTo2 {
            get {
                return ((string)(this["GoogleAppsScriptTranslationTo2"]));
            }
            set {
                this["GoogleAppsScriptTranslationTo2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GoogleAppsScriptTranslationTo1Run {
            get {
                return ((bool)(this["GoogleAppsScriptTranslationTo1Run"]));
            }
            set {
                this["GoogleAppsScriptTranslationTo1Run"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GoogleAppsScriptTranslationTo2Run {
            get {
                return ((bool)(this["GoogleAppsScriptTranslationTo2Run"]));
            }
            set {
                this["GoogleAppsScriptTranslationTo2Run"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DeepLTranslationKey {
            get {
                return ((string)(this["DeepLTranslationKey"]));
            }
            set {
                this["DeepLTranslationKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DeepLTranslationFrom {
            get {
                return ((string)(this["DeepLTranslationFrom"]));
            }
            set {
                this["DeepLTranslationFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DeepLTranslationTo1 {
            get {
                return ((string)(this["DeepLTranslationTo1"]));
            }
            set {
                this["DeepLTranslationTo1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DeepLTranslationTo2 {
            get {
                return ((string)(this["DeepLTranslationTo2"]));
            }
            set {
                this["DeepLTranslationTo2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeepLTranslationTo1Run {
            get {
                return ((bool)(this["DeepLTranslationTo1Run"]));
            }
            set {
                this["DeepLTranslationTo1Run"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeepLTranslationTo2Run {
            get {
                return ((bool)(this["DeepLTranslationTo2Run"]));
            }
            set {
                this["DeepLTranslationTo2Run"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tesseract")]
        public string OcrEngine {
            get {
                return ((string)(this["OcrEngine"]));
            }
            set {
                this["OcrEngine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OcrShortcutKey {
            get {
                return ((string)(this["OcrShortcutKey"]));
            }
            set {
                this["OcrShortcutKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eng")]
        public string TesseractOcrLanguage {
            get {
                return ((string)(this["TesseractOcrLanguage"]));
            }
            set {
                this["TesseractOcrLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TesseractTranslationEngine {
            get {
                return ((string)(this["TesseractTranslationEngine"]));
            }
            set {
                this["TesseractTranslationEngine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ja")]
        public string TesseractTranslationLanguage {
            get {
                return ((string)(this["TesseractTranslationLanguage"]));
            }
            set {
                this["TesseractTranslationLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OcrTranslationEngine {
            get {
                return ((string)(this["OcrTranslationEngine"]));
            }
            set {
                this["OcrTranslationEngine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OcrLanguage {
            get {
                return ((string)(this["OcrLanguage"]));
            }
            set {
                this["OcrLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OcrTranslationLanguage {
            get {
                return ((string)(this["OcrTranslationLanguage"]));
            }
            set {
                this["OcrTranslationLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SubtitlesTranslationEngine {
            get {
                return ((string)(this["SubtitlesTranslationEngine"]));
            }
            set {
                this["SubtitlesTranslationEngine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SubtitlesTranslationLanguageFrom {
            get {
                return ((string)(this["SubtitlesTranslationLanguageFrom"]));
            }
            set {
                this["SubtitlesTranslationLanguageFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SubtitlesVoiceTarget {
            get {
                return ((string)(this["SubtitlesVoiceTarget"]));
            }
            set {
                this["SubtitlesVoiceTarget"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SubtitlesTranslationTarget1 {
            get {
                return ((string)(this["SubtitlesTranslationTarget1"]));
            }
            set {
                this["SubtitlesTranslationTarget1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SubtitlesTranslationTarget2 {
            get {
                return ((string)(this["SubtitlesTranslationTarget2"]));
            }
            set {
                this["SubtitlesTranslationTarget2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SubtitlesIsClearInterval {
            get {
                return ((bool)(this["SubtitlesIsClearInterval"]));
            }
            set {
                this["SubtitlesIsClearInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int SubtitlesClearInterval {
            get {
                return ((int)(this["SubtitlesClearInterval"]));
            }
            set {
                this["SubtitlesClearInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SubtitlesIsAdditionalTime {
            get {
                return ((bool)(this["SubtitlesIsAdditionalTime"]));
            }
            set {
                this["SubtitlesIsAdditionalTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SubtitlesAdditionalTime {
            get {
                return ((int)(this["SubtitlesAdditionalTime"]));
            }
            set {
                this["SubtitlesAdditionalTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SubtitlesTranslation1 {
            get {
                return ((bool)(this["SubtitlesTranslation1"]));
            }
            set {
                this["SubtitlesTranslation1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SubtitlesTranslation2 {
            get {
                return ((bool)(this["SubtitlesTranslation2"]));
            }
            set {
                this["SubtitlesTranslation2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SubtitlesTranslationLanguageTo1 {
            get {
                return ((string)(this["SubtitlesTranslationLanguageTo1"]));
            }
            set {
                this["SubtitlesTranslationLanguageTo1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SubtitlesTranslationLanguageTo2 {
            get {
                return ((string)(this["SubtitlesTranslationLanguageTo2"]));
            }
            set {
                this["SubtitlesTranslationLanguageTo2"] = value;
            }
        }
    }
}
