namespace ObsWebSocket5 {
    public enum ObsMediaInputAction {
        OBS_WEBSOCKET_MEDIA_INPUT_ACTION_NONE = 0,
        OBS_WEBSOCKET_MEDIA_INPUT_ACTION_PLAY = 1,
        OBS_WEBSOCKET_MEDIA_INPUT_ACTION_PAUSE = 2,
        OBS_WEBSOCKET_MEDIA_INPUT_ACTION_STOP = 3,
        OBS_WEBSOCKET_MEDIA_INPUT_ACTION_RESTART = 4,
        OBS_WEBSOCKET_MEDIA_INPUT_ACTION_NEXT = 5,
        OBS_WEBSOCKET_MEDIA_INPUT_ACTION_PREVIOUS = 6
    }
}
